name: mental_health
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  indexed_list_view: ^1.1.5
  screen_loader: ^2.0.1
  redux: ^4.0.0+3
  flutter_redux: ^0.6.0
  email_validator: ^1.0.6
  http: ^0.12.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: Segoe UI
        fonts:
          - asset: lib/fonts/segoeui.ttf
          - asset: lib/fonts/segoeuii.ttf
            style: italic
          - asset: lib/fonts/segoeuib.ttf
            weight: 700
          - asset: lib/fonts/segoeuisl.ttf
            weight: 300  
  assets:
    - lib/assets/

 
  uses-material-design: true

